apiVersion: v1
kind: Service
metadata:
  name: fivoria-frontend
  namespace: fivoria
spec:
  selector:
    app: fivoria-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: LoadBalancer
