apiVersion: v1
kind: Secret
metadata:
  name: fivoria-secret
  namespace: fivoria
type: Opaque
data:
  DB_PASSWORD: Zml2b3JpYV9zZWN1cmVfcGFzc3dvcmRfMjAyNA==
  JWT_SECRET: Zml2b3JpYV9qd3Rfc2VjcmV0X2tleV8yMDI0X3NlY3VyZQ==
  REDIS_PASSWORD: cmVkaXNfc2VjdXJlX3Bhc3N3b3JkXzIwMjQ=
  MYSQL_ROOT_PASSWORD: cm9vdF9wYXNzd29yZF9zZWN1cmVfMjAyNA==
