apiVersion: v1
kind: Service
metadata:
  name: web-api
  namespace: fivoria
  labels:
    app: web-api
    tier: backend
spec:
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: web-api
    tier: backend
  type: ClusterIP
